version: '3.8'

services:
  # OIDC 认证服务
  oidc-server:
    build: ./phoenixcoder-oidc-server
    container_name: phoenixcoder-oidc-server
    ports:
      - "8001:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: phoenixcoder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WECHAT_APPID: ${WECHAT_APPID}
      WECHAT_APPSECRET: ${WECHAT_APPSECRET}
      WECHAT_REDIRECT_URI: http://localhost:8001/wechat/callback
      JWT_SECRET: dev-jwt-secret-key-change-in-production
      ISSUER: http://localhost:8001
    volumes:
      - ./phoenixcoder-oidc-server:/app
    networks:
      - phoenixcoder-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  # 主服务端
  server:
    build: ./phoenixcoder-server
    container_name: phoenixcoder-server
    ports:
      - "8000:8000"
    environment:
      - OIDC_ISSUER=http://oidc-server:8001
      - OIDC_CLIENT_ID=phoenixcoder-client
      - OIDC_CLIENT_SECRET=dev-client-secret
      - OIDC_REDIRECT_URI=http://localhost:3000/auth/callback
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
    volumes:
      - ./phoenixcoder-server:/app
    depends_on:
      - oidc-server
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # 管理端
  admin:
    build: ./phoenixcoder-admin
    container_name: phoenixcoder-admin
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_OIDC_ISSUER=http://localhost:8001
      - REACT_APP_CLIENT_ID=phoenixcoder-admin
    depends_on:
      - server
      - oidc-server
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: phoenixcoder-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - phoenixcoder-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # PostgreSQL 数据库
  postgres:
    image: postgres:14-alpine
    container_name: phoenixcoder-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: phoenixcoder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./phoenixcoder-oidc-server/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - phoenixcoder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d phoenixcoder"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: phoenixcoder-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - phoenixcoder-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: phoenixcoder-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - server
      - oidc-server
      - admin
    networks:
      - phoenixcoder-network
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:
  rabbitmq-data:

networks:
  phoenixcoder-network:
    driver: bridge