version: '3.8'

services:
  # OIDC 认证服务
  oidc-server:
    build: ./phoenixcoder-oidc-server
    container_name: phoenixcoder-oidc-server
    ports:
      - "8001:8001"
    environment:
      - OIDC_ISSUER=http://localhost:8001
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
    volumes:
      - ./phoenixcoder-oidc-server:/app
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # 主服务端
  server:
    build: ./phoenixcoder-server
    container_name: phoenixcoder-server
    ports:
      - "8000:8000"
    environment:
      - OIDC_ISSUER=http://oidc-server:8001
      - OIDC_CLIENT_ID=phoenixcoder-client
      - OIDC_CLIENT_SECRET=dev-client-secret
      - OIDC_REDIRECT_URI=http://localhost:3000/auth/callback
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
    volumes:
      - ./phoenixcoder-server:/app
    depends_on:
      - oidc-server
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # 管理端
  admin:
    build: ./phoenixcoder-admin
    container_name: phoenixcoder-admin
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_OIDC_ISSUER=http://localhost:8001
      - REACT_APP_CLIENT_ID=phoenixcoder-admin
    depends_on:
      - server
      - oidc-server
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: phoenixcoder-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: phoenixcoder-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=phoenixcoder
      - POSTGRES_USER=phoenixcoder
      - POSTGRES_PASSWORD=dev-password-change-in-production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - phoenixcoder-network
    restart: unless-stopped

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: phoenixcoder-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - server
      - oidc-server
      - admin
    networks:
      - phoenixcoder-network
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:

networks:
  phoenixcoder-network:
    driver: bridge 